[package]
name = "gifcap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusttype = "0.9.3"
image = "0.24.7"

[workspace]
members = [
    "."
]